---
title: "Ejercicio clase 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Equipo 10


```{r}
f <- function(x) { 1 / ((x)^2)}
f1 <- function(x) { -2 / (x)^3}
f2 <- function(x) { 6 / (x)^4}
f3 <- function(x) { -24 / (x)^5}
f4 <- function(x) { 120 / (x)^6}

```

```{r}

taylor <-function(x){
  x0 <- -2.5
  f(x0) + f1(x0)*(x-x0) + f2(x0)*(x-x0)^2/2 + f3(x0)*(x-x0)^3/6 +f4(x0)*(x-x0)^4/24
}

```


```{r}
x=seq(-3,-2,length=1000)
fx <- f(x)
tay <- taylor(x)
plot(x,tay,type="p",col="blue",lwd=1, main="Taylor", xlab="", ylab="")
lines(x,fx,col="red",lwd=3)
```




#Ejercicio varias variables

```{r}

fun2 <- function(x1,x2,x3){
  x1*x2*exp(x1^2 + x3^2 - 5)
}

h <- 1*10^(seq(-1,-16,-1))
```

```{r}

g1 <-  (fun2(1 +h, 3,-2) - fun2(1 , 3,-2))/h
g2 <-  (fun2(1, 3 +h,-2) - fun2(1 , 3,-2))/h
g3 <-  (fun2(1, 3,-2 +h) - fun2(1 , 3,-2))/h

grad <- rbind(g1,g2,g3)
g2 <- grad - c(9,1,-12)
g3 <- t(g2 * g2)
norma <- g3[,1] + g3[,2] + g3[,3]
down <- sum( 9*9 + 1*1 + 12*12 )
e <- sqrt(norma)/sqrt(down)

```

```{r}
plot(x = log(h) , y = log(e),type = "b", xlab = "log h", ylab = "log  ErrR")

```




























