---
title: "Multiplicación Matrices"
author: "Soledad, Iker, Luis"
date: "February 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Ejercicio - nota 3.1.1 multiplicación de matrices

Utilizar los productos matriciales o vectoriales para las versiones  que revisamos la clase pasada  
ijk, kij, kikj de la multiplicación de matrices de modo que los dos loops más internos utilicen 
estos productos 


```{r}
#Matrices iniciales
set.seed(73)

A <- matrix(sample(20,16),4,4)
B <- matrix(sample(12,12),4,3)
A
B
```

```{r}
# Matriz resultado
C <-A %*% B
C
```

```{r}
# Algoritmo ijk

matrix_mult_ijk <- function(A,B){
  m <- length(A[,1])
  n <- length(B[1,])
  r <- length(A[1,])
  C <- matrix(0L,nrow = m, ncol = n)
  
  for (i in 1:m){
    C[i,] = C[i,] + A[i,] %*% B
  }
  C
}

matrix_mult_ijk(A,B)

```

```{r}
# Algoritmo jik

matrix_mult_jik <- function(A,B){
  m <- length(A[,1])
  n <- length(B[1,])
  r <- length(A[1,])
  C <- matrix(0L,nrow = m, ncol = n)
  
  for (j in 1:n){
    C[,j] = C[,j] + A %*% B[,j]
  }
  C
}

matrix_mult_jik(A,B)

```

```{r}
# Algoritmo kij

matrix_mult_kij <- function(A,B){
  m <- length(A[,1])
  n <- length(B[1,])
  r <- length(A[1,])
  C <- matrix(0L,nrow = m, ncol = n)
  
  for (k in 1:r){
    C = C + A[,k] %o% B[k,]
  }
  C
}

matrix_mult_kij(A,B)

```

```{r}
# Algoritmo ikj

matrix_mult_ikj <- function(A,B){
  m <- length(A[,1])
  n <- length(B[1,])
  r <- length(A[1,])
  C <- matrix(0L,nrow = m, ncol = n)
  
  for (i in 1:m){
    C[i,] = C[i,] + A[i,] %*% B
  }
  C
}

matrix_mult_ikj(A,B)

```


## Ejercicio 2

Lo resolvimos por sustitución hacia atrás y sutitución hacia delante en papel


```{r}
A_1=matrix(nrow=4,ncol=4, c(4,-1,2,3,0,-2,7,-4,0,0,6,5,0,0,0,3),byrow=TRUE)
b_1=matrix(nrow=4,ncol=1, c(20,-7,4,6),byrow=TRUE)

solve(A_1,b_1)
```



```{r}
A_2=matrix(nrow=4,ncol=4, c(3,0,0,0,-1,1,0,0,3,-2,-1,0,1,-2,6,2),byrow=TRUE)
b_2=matrix(nrow=4,ncol=1, c(5,6,4,2),byrow=TRUE)

solve(A_2,b_2)
```

```{r}
# Algoritmo sustitución hacia atrás

sustitucion_atras <- function(A,b){
  n <- length(A[,1])
  x <- matrix(0L,nrow = n, ncol = 1)
  x[n] = b[n]/A[n,n]
  
  for (i in (n-1):1){
    x[i] = ( b[i] - A[i,(i+1):n] %*% x[(i+1):n] ) / A[i,i]
  }
  x
}


```

```{r}
sustitucion_atras(A_1,b_1)
```

```{r}
# Algoritmo sustitución hacia atrás

sustitucion_atras_rem <- function(A,b){
  n <- length(A[,1])
  ##x <- matrix(0L,nrow = n, ncol = 1)
  b[n] = b[n]/A[n,n]
  
  for (i in (n-1):1){
    b[i] = ( b[i] - A[i,(i+1):n] %*% b[(i+1):n] ) / A[i,i]
  }
  b
}


```

```{r}
sustitucion_atras_rem(A_1,b_1)
```

```{r}
# Algoritmo sustitución hacia atrás

sustitucion_adelante_rem <- function(A,b){
  n <- length(A[,1])
  b[1] = b[1]/A[1,1]
  
  for (i in 2:n){
    b[i] = ( b[i] - A[i,1:(i-1)] %*% b[1:(i-1)] ) / A[i,i]
  }
  b
}


```

```{r}
sustitucion_adelante_rem(A_2,b_2)
```